---
# tasks file for deploy_zabbix_agent

- name: Test connection
  win_ping: 

- name: Check if already installed
  win_stat:
    path: '%ProgramFiles%/Zabbix Agent/zabbix_agentd.exe'
    get_checksum: yes
    checksum_algorithm: md5
  register: md5_checksum

- debug: var=md5_checksum

- name: Check if a service is installed
  win_service:
    name: '{{ SERVICE_NAME }}'
  register: SERVICE_NAME_INFO

- debug: var=SERVICE_NAME_INFO

- block:
  - name: Stop service
    win_service:
      name: '{{ SERVICE_NAME }}'
      state: stopped
  
  - name: Remove agent service
    win_service:
      name: '{{ SERVICE_NAME }}'
      state: absent

  when: 
    - SERVICE_NAME_INFO.exists
    - md5_checksum.stat.checksum != '{{ AGENTD_CHECKSUM_x64 }}'
  
- name: Remove Dirs
  win_file: 
    path: '{{ item }}'
    state: absent
  loop:
    - 'C:/Zabbix'
    - 'C:/Program Files/Zabbix'
    - 'C:/Program Files (x86)/Zabbix'

- name: Install Zabbix Agent x64
  win_package:
    path: '{{ DISTR_FOLDER }}\{{ DISTR_INSTALLER_x64 }}'
    product_id: '{{ PRODUCT_CODE_x64 }}'
    arguments: 'SERVER={{ SERVER_ADDR }}'
  when: ansible_architecture == "64-bit"

- name: Install Zabbix Agent x86
  win_package:
    path: '{{ DISTR_FOLDER }}\{{ DISTR_INSTALLER_x86 }}'
    product_id: '{{ PRODUCT_CODE_x86 }}'
    arguments: 'SERVER={{ SERVER_ADDR }}'
  when: ansible_architecture == "32-bit"

- name: Copy config
  win_copy:
    src: zabbix_agentd.conf
    dest: '%ProgramFiles%/Zabbix Agent/zabbix_agentd.conf'
  notify: Restart Zabbix Agent Service






